repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language: system
        args: [ "backend/" ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        name: ruff
        entry: ./scripts/ruff.sh
        language: system
        types: [ python ]
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: mypy
        entry: ./scripts/mypy.sh
        language: system
        types: [ python ]
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: ./scripts/pytest.sh
        language: system
        pass_filenames: false
