repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [ "backend/" ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff
        language: system
        types: [ python ]
        args: [ "check", "backend/", "--config", "ruff.toml" ]
        pass_filenames: false

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: system
        types: [ python ]
        args: [ "--config-file", "mypy.ini", "backend/" ]
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
        args:
          - "backend/"
          - "--maxfail=1"
          - "--disable-warnings"
