version: '3.8'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    container_name: fastapi_backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend/app:/app/app
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/poetry.lock:/app/poetry.lock
      - ./backend/tests:/app/tests
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ENV=development
      - PYTHONPATH=/app/app
      - MONGO_URI=mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@${MONGO_DB_HOST}:${MONGO_DB_PORT}/${MONGO_DB_NAME}
    networks:
      - my_network
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/app
    environment:
      - ENV=development
    networks:
      - my_network
    depends_on:
      - backend

  mongo:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "${MONGO_DB_PORT}:${MONGO_DB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
    driver: local

networks:
  my_network:
    driver: bridge
