version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ENV=development
      - PYTHONPATH=/app/app
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - ENV=development
    networks:
      - my_network
    depends_on:
      - backend

networks:
  my_network:
    driver: bridge
